FROM openjdk:15

ENV KOTLIN_INSTALL_HOME=/usr/
ENV PATH=/usr/kotlinc/bin:$PATH

RUN yum install -y unzip; \
curl -fL -o kotlin.tgz https://github.com/JetBrains/kotlin/releases/download/v1.3.71/kotlin-compiler-1.3.71.zip; \
unzip /kotlin.tgz -d "$KOTLIN_INSTALL_HOME"; rm /kotlin.tgz; kotlinc -version

CMD ["kotlinc"]