FROM openjdk:15

ARG KOTLIN_VERSION=1.3.72

ENV KOTLIN_INSTALL_HOME=/usr/
ENV PATH=/usr/kotlinc/bin:$PATH

RUN yum install -y unzip; \
curl -fL -o kotlin.tgz https://github.com/JetBrains/kotlin/releases/download/v$KOTLIN_VERSION/kotlin-compiler-$KOTLIN_VERSION.zip; \
unzip /kotlin.tgz -d "$KOTLIN_INSTALL_HOME"; rm /kotlin.tgz; kotlinc -version

CMD ["kotlinc"]